"use client";

import { FormEvent, useEffect, useState } from "react";
import { Artifact, ArtifactViewer, detectArtifact } from "@/components/Artifact/ArtifactViewer";
import { ModelSelector } from "@/components/Chat/ModelSelector";
import { createSession, getSession, Message, Provider, Session } from "@/lib/api";
import { useChatStream } from "@/hooks/useChatStream";

function SourceList({ sources }: { sources: Array<{ source_id: string; episode: string; guest: string | null; timestamp: string | null; topic: string | null; source_url: string }> }) {
  if (!sources.length) return null;
  return <ul className="mt-2 space-y-1 text-xs text-slate-400">{sources.map((source) => <li key={source.source_id}><a href={source.source_url} target="_blank" rel="noreferrer" className="text-cyan-300">[{source.source_id}] {source.episode}</a>{source.guest ? ` — ${source.guest}` : ""}{source.timestamp ? ` · ${source.timestamp}` : ""}{source.topic ? ` · ${source.topic}` : ""}</li>)}</ul>;
}

export default function Home() {
  const [session, setSession] = useState<Session | null>(null); const [input, setInput] = useState(""); const [provider, setProvider] = useState<Provider>("ollama"); const [artifactOpen, setArtifactOpen] = useState(true); const [artifact, setArtifact] = useState<Artifact | null>(null); const { streamingText, sources, loading, error, send } = useChatStream();
  const start = () => createSession("New conversation").then(setSession).catch(() => undefined);
  useEffect(() => { start(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!session || !input.trim() || loading) return; const content = input.trim(); setInput(""); const user: Message = { id: crypto.randomUUID(), role: "user", content, provider: null, model: null, source_metadata: null, created_at: new Date().toISOString() }; setSession({ ...session, messages: [...session.messages, user] }); const response = await send(session.id, content, provider); if (response) { setArtifact(detectArtifact(response.answer)); setSession((current) => current ? { ...current, messages: [...current.messages, { id: crypto.randomUUID(), role: "assistant", content: response.answer, provider: response.retrieval_metadata.provider, model: response.retrieval_metadata.model, source_metadata: { sources: response.sources }, created_at: new Date().toISOString() }] } : current); } };
  if (!session) return <main className="p-6 text-slate-300">Creating session…</main>;
  return <main className="grid h-screen grid-cols-1 gap-4 p-4 lg:grid-cols-[1.2fr_0.8fr]"><section className="flex min-h-0 flex-col rounded-xl bg-slate-950 p-4"><header className="mb-3 flex items-center justify-between"><div><button onClick={start} className="rounded bg-slate-800 px-3 py-1 text-xs">New session</button><button onClick={() => getSession(session.id).then(setSession).catch(() => undefined)} className="ml-2 rounded bg-slate-800 px-3 py-1 text-xs">Refresh</button></div><ModelSelector value={provider} onChange={setProvider} /></header><div className="flex-1 space-y-3 overflow-auto">{session.messages.map((message) => <article key={message.id} className="rounded-lg bg-slate-800 p-3"><div className="text-xs uppercase text-slate-400">{message.role}{message.provider ? ` · ${message.provider}` : ""}</div><div className="whitespace-pre-wrap text-sm">{message.content}</div><SourceList sources={message.source_metadata?.sources ?? []} /></article>)}{loading && <article className="rounded-lg bg-slate-800 p-3"><div className="text-xs uppercase text-slate-400">Assistant · streaming</div><div className="whitespace-pre-wrap text-sm">{streamingText || "Retrieving grounded sources…"}</div><SourceList sources={sources} /></article>}</div>{error && <p role="alert" className="mt-2 rounded bg-red-950 p-2 text-sm text-red-200">{error}</p>}<form onSubmit={submit} className="mt-3 flex gap-2"><textarea value={input} onChange={(event) => setInput(event.target.value)} className="min-h-12 flex-1 rounded bg-slate-800 p-3 text-sm" placeholder="Ask about Lenny's podcast archive…"/><button disabled={loading} className="rounded bg-cyan-600 px-4 text-sm disabled:opacity-50">Send</button></form></section><aside className="min-h-0 rounded-xl bg-slate-950 p-4"><button onClick={() => setArtifactOpen((open) => !open)} className="text-sm text-slate-300">{artifactOpen ? "Hide" : "Show"} artifact panel</button>{artifactOpen && <div className="mt-4 h-[calc(100%-3rem)]"><ArtifactViewer artifact={artifact} /></div>}</aside></main>;
}
